GAE cert validation fails with CloudFlare; disable
Results in error:
    SSLCertificateError: Invalid and/or missing SSL certificate for URL: https://auth.lessigforpresident.com/v1/current_user?return_to=https%3A%2F%2Flocalhost%3A8080%2F

see http://stackoverflow.com/questions/13755041/invalid-and-or-missing-ssl-certificate