Generate testing Team key dynamically instead of hard-coded
It seems Google App Engine object keys implicitly embed their AppID
So this was failing with `BadRequestError`:

    BadRequestError: app "dev~lessig-team" cannot access app
    "dev~mayday-pac-teams"'s data